### ISSUE TITLE
RuntimeError: invalid argument 3: out of range at /opt/conda/conda-bld/pytorch_1565272279342/work/aten/src/TH/generic/THTensor.cpp:370

### ISSUE THREAD

**Issue by nushrathumaira** [UtopAIBuilder/GENERATING-NATURAL-LANGUAGE-EXPLANATION-FOR-RECOMMENDATION#1]
Hi,

I was running the notebook and this error emerged. Could you help me how to solve this please. Following is the traceback

Traceback (most recent call last):
  File "explanation_generation.py", line 419, in <module>
    nlp_loss, rating_loss = training(model,train_loader, optimizer,NLP_criterion,Rating_criterion, clip, scaling_factor)
  File "explanation_generation.py", line 384, in training
    decoder_outputs, ratings = model(u,i,rev) # normailized decoder output
  File "/home/nhumair/.conda/envs/torch1_2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "explanation_generation.py", line 325, in forward
    h_0 = self.getInitialHiddenState(C_0)
  File "explanation_generation.py", line 296, in getInitialHiddenState
    atten_score = self.attention(C_0).unsqueeze(1)
  File "explanation_generation.py", line 269, in attention
    h = h.unsqueeze(1).repeat(1,src_len,1) # [num_layers*batch_size, n_features, hidden_dim]

Also amazon 5 core doesn't any key called 'sentence' in the reviews. can you share your input file for reviews, at least partially.
Thanks.

**Comment by UtopAIBuilder** [comment]
If you read the implemented paper, what the auhors do is extract feature words from the review. The link they mentioned for the tool used for extraction was not working. But anyway I made it work by going through the author's website. The missing file is the review.pickle, which containes the extracted 'sentence' and all. I am attaching the link for the same [https://drive.google.com/file/d/1xqYNKk0tjV6_91iqHAKpfY_XES2DMxx5/view?usp=sharing] 
Also you might want to work on the data preprocessing for good results, for eg: some reviews are of more than 100 sentences long while some had only one sentence. Even the sentence length too has high variance, one word to 100. blind chopping will result badly.
